### ISSUE TITLE
chore(workflows): add concurrency to CI and CD workflows

### ISSUE THREAD

**Issue by peterjokumsen** [chill-viking/ng-libs#119]
### Description

Get CI and CD workflows to skip when action runs for newer commit.

### Sample of Change

add concurrency to each workflow:

```yaml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
